const Books = ({ books }) => {
  const filteredBooks = books.filter(
    (book) => book.genre === "Science Fiction"
  );

  const bookListing = filteredBooks.map((book) => (
    <div key={book.id}>
      <h2>{book.title}</h2>
      <p>Genre: {book.genre}</p>
    </div>
  ));

  return (
    <>
      <h1>Books Detail</h1>
      {bookListing}
    </>
  );
};

const Users = ({ users }) => {
  const filteredUsers = users.filter((user) => user.role === "Admin");

  const userListing = filteredUsers.map((user) => (
    <div key={user.id}>
      <h2>{user.name}</h2>
      <p>Role: {user.role}</p>
    </div>
  ));

  return (
    <>
      <h1>Users Detail</h1>
      {userListing}
    </>
  );
};

const Products = ({ products }) => {
  const filteredProducts = products.filter((product) => product.price > 100);

  const productListing = filteredProducts.map((product) => (
    <div key={product.id}>
      <h2>{product.name}</h2>
      <p>Price: {product.price}</p>
      <p>Color: {product.features.color}</p>
      <p>{product.features.isWaterProof ? "Water Poof" : "Not Water Proof"}</p>
    </div>
  ));

  return (
    <>
      <h1>Products Detail</h1>
      {productListing}
    </>
  );
};

const Cities = ({ cities }) => {
  const filteredCities = cities.filter((city) => city.population > 1000000);

  const cityListing = filteredCities.map((city) => (
    <div key={city.id}>
      <h2>{city.name}</h2>
      <p>Population: {city.population}</p>
    </div>
  ));

  return (
    <>
      <h1>Cities Data</h1>
      {cityListing}
    </>
  );
};

const Movies = ({ movies }) => {
  const filterMovies = movies.filter((movie) => movie.releaseYear > 2015);

  const movieListing = filterMovies.map((movie) => (
    <div key={movie.id}>
      <h2>{movie.title}</h2>
      <p>Release Year: {movie.releaseYear}</p>
    </div>
  ));

  return (
    <>
      <h1>Movies Detail</h1>
      {movieListing}
    </>
  );
};

const Podcasts = ({ podcasts }) => {
  const filteredPodcast = podcasts.filter((podcast) => podcast.featured);

  const podcastListing = filteredPodcast.map((podcast) => (
    <div key={podcast.id}>
      <h2>{podcast.title}</h2>
      <p>Hosts: {podcast.host.join(", ")}</p>
      <p>{podcast.featured ? "Featured" : "Not Featured"}</p>
    </div>
  ));

  return (
    <>
      <h1>Podcasts Detail</h1>
      {podcastListing}
    </>
  );
};

const Tasks = ({ tasks }) => {
  const total = tasks.reduce(
    (acc, curr) => (curr.completed ? acc + 1 : acc),
    0
  );

  return (
    <div>
      <h1>Total Number of Tasks Completed</h1>
      <p>Total Number: {total}</p>
    </div>
  );
};

const MoviesDetails = ({ movies }) => {
  const filteredMovies = movies.filter((movie) => movie.releaseYear > 2000);

  const totalDuration = filteredMovies.reduce(
    (acc, curr) => acc + curr.duration,
    0
  );
  const avgDuration = totalDuration / filteredMovies.length;

  return (
    <div>
      <h1>Average Duration of Movies</h1>
      <p>Average Duration : {avgDuration}</p>
    </div>
  );
};

const Vehicles = ({ vehicles }) => {
  const totalDistance = vehicles.reduce((acc, curr) => acc + curr.distance, 0);

  return (
    <div>
      <h1>Total Distance Traveled</h1>
      <p>Total Distance: {totalDistance}</p>
    </div>
  );
};

const Sales = ({ sales }) => {
  const totalRevenue = sales.reduce(
    (acc, curr) => curr.quantity * curr.price + acc,
    0
  );

  return (
    <div>
      <h1>Total Revenue Generated By all Sales Transaction</h1>
      <p>Total Revenue: {totalRevenue}</p>
    </div>
  );
};

const App = () => {
  const sales = [
    { id: 1, product: "Widget A", price: 25, quantity: 10 },

    { id: 2, product: "Gadget B", price: 50, quantity: 5 },

    { id: 3, product: "Tool C", price: 30, quantity: 8 },
  ];

  const vehicles = [
    { id: 1, name: "Car", distance: 150 },

    { id: 2, name: "Bicycle", distance: 10 },

    { id: 3, name: "Motorcycle", distance: 75 },
  ];

  const moviesArray = [
    { id: 1, title: "The Matrix", duration: 136, releaseYear: 1999 },

    { id: 2, title: "Inception", duration: 148, releaseYear: 2010 },

    { id: 3, title: "Avatar", duration: 162, releaseYear: 2009 },
  ];

  const books = [
    { id: 1, title: "Dune", genre: "Science Fiction" },

    { id: 2, title: "Neuromancer", genre: "Science Fiction" },

    { id: 3, title: "Foundation", genre: "Sci-fi" },
  ];

  const users = [
    { id: 1, name: "Alice", role: "User" },

    { id: 2, name: "Bob", role: "Admin" },

    { id: 3, name: "Charlie", role: "User" },

    { id: 4, name: "John", role: "Admin" },
  ];

  const products = [
    {
      id: 1,
      name: "Laptop",
      price: 1200,
      features: { color: "green", isWaterProof: false },
    },

    {
      id: 2,
      name: "Smartphone",
      price: 800,
      features: { color: "blue", isWaterProof: true },
    },

    {
      id: 3,
      name: "Headphones",
      price: 150,
      features: { color: "silver", isWaterProof: false },
    },
  ];

  const cities = [
    { id: 1, name: "New York", population: 8500000 },

    { id: 2, name: "Los Angeles", population: 539900 },

    { id: 3, name: "Chicago", population: 2700000 },
  ];

  const movies = [
    { id: 1, title: "Inception", releaseYear: 2010 },

    { id: 2, title: "La La Land", releaseYear: 2016 },

    { id: 3, title: "Interstellar", releaseYear: 2014 },

    { id: 4, title: "Dune 2", releaseYear: 2024 },
  ];

  const podcasts = [
    { id: 1, title: "Tech Talk", host: ["host 1"], featured: true },

    { id: 2, title: "Business Insights", host: ["host 2"], featured: false },

    {
      id: 3,
      title: "Science Hour",
      host: ["host 3", "host 4"],
      featured: true,
    },
  ];

  const tasks = [
    { id: 1, description: "Complete project proposal", completed: true },

    { id: 2, description: "Review client feedback", completed: false },

    { id: 3, description: "Submit final report", completed: true },
  ];

  return (
    <div>
      <Books books={books} />
      <hr />
      <Users users={users} />
      <hr />
      <Products products={products} />
      <hr />
      <Cities cities={cities} />
      <hr />
      <Movies movies={movies} />
      <hr />
      <Podcasts podcasts={podcasts} />
      <hr />
      <MoviesDetails movies={moviesArray} />
      <hr />
      <Tasks tasks={tasks} />
      <hr />
      <Vehicles vehicles={vehicles} />
      <hr />
      <Sales sales={sales} />
    </div>
  );
};

export default App;
